version: "3"
services:
  db:
    image: mysql:8.0.20
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    environment:
      RAILS_SERVE_STATIC_FILES: "1"
      EDITOR: "vim"
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
